app_version: 1
number_of_times_to_poll: 7
concurrency: 5
#store:
#  type: parquet
#  path: out/data/movie_provider_db
store:
  type: memory
# query_engine:
#   type: pandas
query_engine:
  type: custom
movie_data_providers:
  - name: filmworld
    base_url: https://webjetapitest.azurewebsites.net/api/
    summary_api: filmworld/movies/
    details_api: filmworld/movie/
    timeout: 10
  - name: cinemaworld
    base_url: https://webjetapitest.azurewebsites.net/api/
    summary_api: cinemaworld/movies/
    details_api: cinemaworld/movie/
    timeout: 10



